/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq;


import com.wordpress.kkaravitis.pricing.jooq.tables.CompetitorPrice;
import com.wordpress.kkaravitis.pricing.jooq.tables.FlywaySchemaHistory;
import com.wordpress.kkaravitis.pricing.jooq.tables.ProductPriceResults;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_PRODUCT_TIME = Internal.createIndex(DSL.name("idx_product_time"), ProductPriceResults.PRODUCT_PRICE_RESULTS, new OrderField[] { ProductPriceResults.PRODUCT_PRICE_RESULTS.PRODUCT_ID, ProductPriceResults.PRODUCT_PRICE_RESULTS.TIMESTAMP.desc() }, false);
    public static final Index IX_COMPETITOR_PRICE_UPDATED = Internal.createIndex(DSL.name("ix_competitor_price_updated"), CompetitorPrice.COMPETITOR_PRICE, new OrderField[] { CompetitorPrice.COMPETITOR_PRICE.UPDATED_AT.desc() }, false);
}
