/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq;


import com.wordpress.kkaravitis.pricing.jooq.tables.CompetitorPrice;
import com.wordpress.kkaravitis.pricing.jooq.tables.FlywaySchemaHistory;
import com.wordpress.kkaravitis.pricing.jooq.tables.ProductPriceResults;
import com.wordpress.kkaravitis.pricing.jooq.tables.records.CompetitorPriceRecord;
import com.wordpress.kkaravitis.pricing.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.wordpress.kkaravitis.pricing.jooq.tables.records.ProductPriceResultsRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CompetitorPriceRecord> COMPETITOR_PRICE_PKEY = Internal.createUniqueKey(CompetitorPrice.COMPETITOR_PRICE, DSL.name("competitor_price_pkey"), new TableField[] { CompetitorPrice.COMPETITOR_PRICE.ID }, true);
    public static final UniqueKey<CompetitorPriceRecord> COMPETITOR_PRICE_PRODUCT_ID_KEY = Internal.createUniqueKey(CompetitorPrice.COMPETITOR_PRICE, DSL.name("competitor_price_product_id_key"), new TableField[] { CompetitorPrice.COMPETITOR_PRICE.PRODUCT_ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<ProductPriceResultsRecord> PRODUCT_PRICE_RESULTS_PKEY = Internal.createUniqueKey(ProductPriceResults.PRODUCT_PRICE_RESULTS, DSL.name("product_price_results_pkey"), new TableField[] { ProductPriceResults.PRODUCT_PRICE_RESULTS.ID }, true);
    public static final UniqueKey<ProductPriceResultsRecord> UQ_PRODUCT_TIME = Internal.createUniqueKey(ProductPriceResults.PRODUCT_PRICE_RESULTS, DSL.name("uq_product_time"), new TableField[] { ProductPriceResults.PRODUCT_PRICE_RESULTS.PRODUCT_ID, ProductPriceResults.PRODUCT_PRICE_RESULTS.TIMESTAMP }, true);
}
