/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq;


import com.wordpress.kkaravitis.pricing.jooq.tables.CompetitorPrice;
import com.wordpress.kkaravitis.pricing.jooq.tables.FlywaySchemaHistory;
import com.wordpress.kkaravitis.pricing.jooq.tables.ProductPriceResults;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.competitor_price</code>.
     */
    public final CompetitorPrice COMPETITOR_PRICE = CompetitorPrice.COMPETITOR_PRICE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.product_price_results</code>.
     */
    public final ProductPriceResults PRODUCT_PRICE_RESULTS = ProductPriceResults.PRODUCT_PRICE_RESULTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CompetitorPrice.COMPETITOR_PRICE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            ProductPriceResults.PRODUCT_PRICE_RESULTS
        );
    }
}
