/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq;


import com.wordpress.kkaravitis.pricing.jooq.tables.CompetitorPrice;
import com.wordpress.kkaravitis.pricing.jooq.tables.FlywaySchemaHistory;
import com.wordpress.kkaravitis.pricing.jooq.tables.ProductPriceResults;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.competitor_price</code>.
     */
    public static final CompetitorPrice COMPETITOR_PRICE = CompetitorPrice.COMPETITOR_PRICE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.product_price_results</code>.
     */
    public static final ProductPriceResults PRODUCT_PRICE_RESULTS = ProductPriceResults.PRODUCT_PRICE_RESULTS;
}
