/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq.tables.daos;


import com.wordpress.kkaravitis.pricing.jooq.tables.CompetitorPrice;
import com.wordpress.kkaravitis.pricing.jooq.tables.records.CompetitorPriceRecord;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Optional;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompetitorPriceDao extends DAOImpl<CompetitorPriceRecord, com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice, Long> {

    /**
     * Create a new CompetitorPriceDao without any configuration
     */
    public CompetitorPriceDao() {
        super(CompetitorPrice.COMPETITOR_PRICE, com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice.class);
    }

    /**
     * Create a new CompetitorPriceDao with an attached configuration
     */
    public CompetitorPriceDao(Configuration configuration) {
        super(CompetitorPrice.COMPETITOR_PRICE, com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice.class, configuration);
    }

    @Override
    public Long getId(com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(CompetitorPrice.COMPETITOR_PRICE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchById(Long... values) {
        return fetch(CompetitorPrice.COMPETITOR_PRICE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice fetchOneById(Long value) {
        return fetchOne(CompetitorPrice.COMPETITOR_PRICE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchOptionalById(Long value) {
        return fetchOptional(CompetitorPrice.COMPETITOR_PRICE.ID, value);
    }

    /**
     * Fetch records that have <code>product_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchRangeOfProductId(String lowerInclusive, String upperInclusive) {
        return fetchRange(CompetitorPrice.COMPETITOR_PRICE.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_id IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchByProductId(String... values) {
        return fetch(CompetitorPrice.COMPETITOR_PRICE.PRODUCT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>product_id = value</code>
     */
    public com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice fetchOneByProductId(String value) {
        return fetchOne(CompetitorPrice.COMPETITOR_PRICE.PRODUCT_ID, value);
    }

    /**
     * Fetch a unique record that has <code>product_id = value</code>
     */
    public Optional<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchOptionalByProductId(String value) {
        return fetchOptional(CompetitorPrice.COMPETITOR_PRICE.PRODUCT_ID, value);
    }

    /**
     * Fetch records that have <code>product_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchRangeOfProductName(String lowerInclusive, String upperInclusive) {
        return fetchRange(CompetitorPrice.COMPETITOR_PRICE.PRODUCT_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_name IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchByProductName(String... values) {
        return fetch(CompetitorPrice.COMPETITOR_PRICE.PRODUCT_NAME, values);
    }

    /**
     * Fetch records that have <code>competitor_price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchRangeOfCompetitorPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(CompetitorPrice.COMPETITOR_PRICE.COMPETITOR_PRICE_, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>competitor_price IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchByCompetitorPrice(BigDecimal... values) {
        return fetch(CompetitorPrice.COMPETITOR_PRICE.COMPETITOR_PRICE_, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchRangeOfUpdatedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(CompetitorPrice.COMPETITOR_PRICE.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.CompetitorPrice> fetchByUpdatedAt(OffsetDateTime... values) {
        return fetch(CompetitorPrice.COMPETITOR_PRICE.UPDATED_AT, values);
    }
}
