/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq.tables.daos;


import com.wordpress.kkaravitis.pricing.jooq.tables.ProductPriceResults;
import com.wordpress.kkaravitis.pricing.jooq.tables.records.ProductPriceResultsRecord;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProductPriceResultsDao extends DAOImpl<ProductPriceResultsRecord, com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults, Long> {

    /**
     * Create a new ProductPriceResultsDao without any configuration
     */
    public ProductPriceResultsDao() {
        super(ProductPriceResults.PRODUCT_PRICE_RESULTS, com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults.class);
    }

    /**
     * Create a new ProductPriceResultsDao with an attached configuration
     */
    public ProductPriceResultsDao(Configuration configuration) {
        super(ProductPriceResults.PRODUCT_PRICE_RESULTS, com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults.class, configuration);
    }

    @Override
    public Long getId(com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchById(Long... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults fetchOneById(Long value) {
        return fetchOne(ProductPriceResults.PRODUCT_PRICE_RESULTS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchOptionalById(Long value) {
        return fetchOptional(ProductPriceResults.PRODUCT_PRICE_RESULTS.ID, value);
    }

    /**
     * Fetch records that have <code>product_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfProductId(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.PRODUCT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_id IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByProductId(String... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>product_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfProductName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.PRODUCT_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>product_name IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByProductName(String... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.PRODUCT_NAME, values);
    }

    /**
     * Fetch records that have <code>price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByPrice(BigDecimal... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.PRICE, values);
    }

    /**
     * Fetch records that have <code>currency BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfCurrency(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.CURRENCY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>currency IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByCurrency(String... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.CURRENCY, values);
    }

    /**
     * Fetch records that have <code>timestamp BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfTimestamp(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.TIMESTAMP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByTimestamp(LocalDateTime... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>demand_metric BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfDemandMetric(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.DEMAND_METRIC, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>demand_metric IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByDemandMetric(Double... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.DEMAND_METRIC, values);
    }

    /**
     * Fetch records that have <code>competitor_price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfCompetitorPrice(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.COMPETITOR_PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>competitor_price IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByCompetitorPrice(Double... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.COMPETITOR_PRICE, values);
    }

    /**
     * Fetch records that have <code>inventory_level BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfInventoryLevel(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.INVENTORY_LEVEL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>inventory_level IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByInventoryLevel(Double... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.INVENTORY_LEVEL, values);
    }

    /**
     * Fetch records that have <code>model_prediction BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchRangeOfModelPrediction(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ProductPriceResults.PRODUCT_PRICE_RESULTS.MODEL_PREDICTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>model_prediction IN (values)</code>
     */
    public List<com.wordpress.kkaravitis.pricing.jooq.tables.pojos.ProductPriceResults> fetchByModelPrediction(BigDecimal... values) {
        return fetch(ProductPriceResults.PRODUCT_PRICE_RESULTS.MODEL_PREDICTION, values);
    }
}
