/*
 * This file is generated by jOOQ.
 */
package com.wordpress.kkaravitis.pricing.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CompetitorPrice implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String productId;
    private String productName;
    private BigDecimal competitorPrice;
    private OffsetDateTime updatedAt;

    public CompetitorPrice() {}

    public CompetitorPrice(CompetitorPrice value) {
        this.id = value.id;
        this.productId = value.productId;
        this.productName = value.productName;
        this.competitorPrice = value.competitorPrice;
        this.updatedAt = value.updatedAt;
    }

    public CompetitorPrice(
        Long id,
        String productId,
        String productName,
        BigDecimal competitorPrice,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.productId = productId;
        this.productName = productName;
        this.competitorPrice = competitorPrice;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.competitor_price.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.competitor_price.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.competitor_price.product_id</code>.
     */
    public String getProductId() {
        return this.productId;
    }

    /**
     * Setter for <code>public.competitor_price.product_id</code>.
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * Getter for <code>public.competitor_price.product_name</code>.
     */
    public String getProductName() {
        return this.productName;
    }

    /**
     * Setter for <code>public.competitor_price.product_name</code>.
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Getter for <code>public.competitor_price.competitor_price</code>.
     */
    public BigDecimal getCompetitorPrice() {
        return this.competitorPrice;
    }

    /**
     * Setter for <code>public.competitor_price.competitor_price</code>.
     */
    public void setCompetitorPrice(BigDecimal competitorPrice) {
        this.competitorPrice = competitorPrice;
    }

    /**
     * Getter for <code>public.competitor_price.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.competitor_price.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CompetitorPrice other = (CompetitorPrice) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.productId == null) {
            if (other.productId != null)
                return false;
        }
        else if (!this.productId.equals(other.productId))
            return false;
        if (this.productName == null) {
            if (other.productName != null)
                return false;
        }
        else if (!this.productName.equals(other.productName))
            return false;
        if (this.competitorPrice == null) {
            if (other.competitorPrice != null)
                return false;
        }
        else if (!this.competitorPrice.equals(other.competitorPrice))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.productId == null) ? 0 : this.productId.hashCode());
        result = prime * result + ((this.productName == null) ? 0 : this.productName.hashCode());
        result = prime * result + ((this.competitorPrice == null) ? 0 : this.competitorPrice.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CompetitorPrice (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(productName);
        sb.append(", ").append(competitorPrice);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
